# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  github: liugezhou

user:
  name: liugezhou
  avatar: /images/time.png
  location: Beijing
  description: Talk is cheap Show me the code!
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: false
  repo:  # your blog repo
  
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: true # 开启评论功能
  appId: Ci6gl5SnXOdXxv9BTlQx3T2F-gzGzoHsz
  appKey: bWsfs1hg9qURRp3gJ6SJU41x

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/time.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id: 65352c5d0937b81633dc41def4cba000

# picture of about page
about_pic: time.png

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: 